apiVersion: v1
kind: Service
metadata:
  name: service-pedidos
spec:
  type: LoadBalancer
  selector:
    app: pedidos
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8080
    nodePort: 30001