openapi: 3.0.1
info:
  title: API para Controle de Pedidos - FIAP
  description: Documentação da API para o totem de autoatendimento.
  version: 1.0.0

paths:
  /api/v1/customers:
    post:
      summary: Criar novo cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDTO'
      responses:
        '201':
          description: Cliente criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDTO'
        '400':
          description: Requisição inválida (validação ou erro de negócio)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      summary: Listar clientes com paginação
      parameters:
        - name: page
          in: query
          schema:
            type: integer
        - name: size
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Lista de clientes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedResponseCustomerDTO'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/customers/{cpf}:
    get:
      summary: Buscar cliente por CPF
      parameters:
        - name: cpf
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cliente encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDTO'
        '404':
          description: Cliente não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/customers/{id}:
    delete:
      summary: Deletar cliente por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Cliente deletado com sucesso
        '404':
          description: Cliente não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CustomerDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        cpf:
          type: string
          description: CPF válido
          example: 38968877009
        nome:
          type: string
          description: Nome do cliente
          example: Joaquim da Silva
        email:
          type: string
          format: email
          example: meuemail@gmail.com
          description: Email do cliente
      required:
        - cpf
        - nome
        - email

    PagedResponseCustomerDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/CustomerDTO'
        pageable:
          type: object
        totalPages:
          type: integer
        totalElements:
          type: integer
        last:
          type: boolean
        first:
          type: boolean
        size:
          type: integer
        number:
          type: integer

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Mensagem de erro
        timestamp:
          type: string
          format: date-time
          description: Data e hora do erro
