apiVersion: v1
kind: Service
metadata:
  name: controlepedidos
  namespace: controle-pedidos
spec:
  type: LoadBalancer
  selector:
    app: controlepedidos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
