apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos-deployment
spec:
  selector:
    matchLabels:
      app: pedidos
  replicas: 1
  template:
    metadata:
      labels:
        app: pedidos
    spec:
      containers:
      - name: pedidos
        image: acrprincipal.azurecr.io/imagemprincipal:v1
        ports:
        - containerPort: 8080
        env: 
        - name: SPRING_DATASOURCE_URL 
          value: "jdbc:mysql://mysql:3306/controle_pedidos?connectTimeout=30000"
        - name: SPRING_DATASOURCE_USERNAME 
          value: "spring"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "spring"
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"