name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'correto'
          java-version: 21
      - name: Running Tests
        run: mvn -B test --file pom.xml